# Generated by Django 3.1.7 on 2021-03-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestBook',
            new_name='Entry',
        ),
    ]
