# Generated by Django 3.1.7 on 2021-03-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_auto_20210306_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default=('active', 'Active'), max_length=10, verbose_name='Status'),
        ),
    ]
